// Narsh 2026 — Guest Data Module
// AUTO-GENERATED by build-guests.js from guests.csv — do not edit by hand.
// To change guests, edit guests.csv and re-run: node narsh2026/our-people/build-guests.js

const NARSH_GUESTS = (() => {
  "use strict";

  const GROUPS = [
    {
      "id": "natalies-family",
      "label": "Natalie's Family",
      "color": "#D4A843"
    },
    {
      "id": "arashs-family",
      "label": "Arash's Family",
      "color": "#2A9D8F"
    },
    {
      "id": "meta-coworkers",
      "label": "Meta Coworkers",
      "color": "#C2704F"
    },
    {
      "id": "seattleite",
      "label": "Seattleite",
      "color": "#6B8E9E"
    },
    {
      "id": "waterloo",
      "label": "Waterloo",
      "color": "#A8763E"
    },
    {
      "id": "cayman-crew",
      "label": "Cayman Crew",
      "color": "#C9928E"
    },
    {
      "id": "abby-friends",
      "label": "Abby Friends",
      "color": "#B07D62"
    },
    {
      "id": "stripe-coworkers",
      "label": "Stripe Coworkers",
      "color": "#8E7CC3"
    }
  ];

  const CITIES = [
    {
      "id": "seattle",
      "label": "Seattle"
    },
    {
      "id": "grand-cayman",
      "label": "Grand Cayman"
    },
    {
      "id": "waterloo",
      "label": "Waterloo"
    },
    {
      "id": "mumbai",
      "label": "Mumbai"
    },
    {
      "id": "auckland",
      "label": "Auckland"
    }
  ];

  const GUESTS = [
    {
      "id": "natalie",
      "name": "Natalie Fleury",
      "photo": "/narsh2026/images/people/natalie.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [
        "seattle",
        "grand-cayman",
        "waterloo"
      ],
      "isCouple": true,
      "funFact": "Can name every iguana species native to the Cayman Islands.",
      "connectionToCouple": "The couple (you two!)",
      "householdId": null,
      "side": "natalie",
      "parents": [
        "shawna-morehouse",
        "william-fleury"
      ],
      "inferredParents": []
    },
    {
      "id": "arash",
      "name": "Arash Rai",
      "photo": "/narsh2026/images/people/arash.jpg",
      "groups": [
        "arashs-family"
      ],
      "cities": [
        "seattle",
        "mumbai",
        "auckland",
        "waterloo"
      ],
      "isCouple": true,
      "funFact": "Has lived on four continents before turning twenty.",
      "connectionToCouple": "The couple (you two!)",
      "householdId": null,
      "side": "arash",
      "parents": [
        "jatinder-kaur",
        "amritpal-rai"
      ],
      "inferredParents": []
    },
    {
      "id": "cindy-fleury",
      "name": "Cindy Fleury",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-cindy-fleury",
      "side": "natalie",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "rene-fleury",
      "name": "Rene Fleury",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-cindy-fleury",
      "side": "natalie",
      "parents": [
        "mary-fleury"
      ],
      "inferredParents": []
    },
    {
      "id": "katelyn-henry",
      "name": "Katelyn Henry",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-katelyn-henry",
      "side": "natalie",
      "parents": [
        "guest"
      ],
      "inferredParents": []
    },
    {
      "id": "natreisha-henry",
      "name": "Natreisha Henry",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-katelyn-henry",
      "side": "natalie",
      "parents": [
        "guest"
      ],
      "inferredParents": []
    },
    {
      "id": "kyle-francis",
      "name": "Kyle Francis",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-kendra-kusick",
      "side": "natalie",
      "parents": [
        "rosanne-fleury"
      ],
      "inferredParents": []
    },
    {
      "id": "gabrielle-blumer",
      "name": "Gabrielle Blumer",
      "photo": "/narsh2026/images/people/gabrielle.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gabrielle-blumer",
      "side": "natalie",
      "parents": [
        "steve-blumer",
        "rosanne-fleury"
      ],
      "inferredParents": []
    },
    {
      "id": "ben-blumer",
      "name": "Ben Blumer",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "steve-blumer"
      ],
      "inferredParents": []
    },
    {
      "id": "jennifer-reimer",
      "name": "Jennifer Reimer",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-glen-antle",
      "side": "natalie",
      "parents": [
        "rene-fleury"
      ],
      "inferredParents": []
    },
    {
      "id": "glen-antle",
      "name": "Glen Antle",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-glen-antle",
      "side": "natalie",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "jillian-reimer",
      "name": "Jillian Reimer",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-glen-antle",
      "side": "natalie",
      "parents": [
        "glen-antle",
        "jennifer-reimer"
      ],
      "inferredParents": []
    },
    {
      "id": "shiloh-riddell",
      "name": "Shiloh Riddell",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-isaiah-riddell",
      "side": "natalie",
      "parents": [
        "serenity-blumer"
      ],
      "inferredParents": []
    },
    {
      "id": "taliah-riddell",
      "name": "Taliah Riddell",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-isaiah-riddell",
      "side": "natalie",
      "parents": [
        "serenity-blumer"
      ],
      "inferredParents": []
    },
    {
      "id": "serenity-blumer",
      "name": "Serenity Blumer",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-isaiah-riddell",
      "side": "natalie",
      "parents": [
        "steve-blumer"
      ],
      "inferredParents": []
    },
    {
      "id": "isaiah-riddell",
      "name": "Isaiah Riddell",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-isaiah-riddell",
      "side": "natalie",
      "parents": [
        "serenity-blumer"
      ],
      "inferredParents": []
    },
    {
      "id": "sumita-barahmand",
      "name": "Sumita Barahmand",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-farzad-sangi",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "farzad-sangi",
      "name": "Farzad Sangi",
      "photo": null,
      "groups": [
        "meta-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-farzad-sangi",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "susan-macrae",
      "name": "Susan MacRae",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "jerry-liu",
      "name": "Jerry Liu",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-georgia-hong",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "georgia-hong",
      "name": "Georgia Hong",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-georgia-hong",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "kendra-kusick",
      "name": "Kendra Kusick",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-kendra-kusick",
      "side": "natalie",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "amy-qiu",
      "name": "Amy Qiu",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-amy-qiu",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "phillip-vo",
      "name": "Phillip Vo",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-amy-qiu",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "shawna-morehouse",
      "name": "Shawna Morehouse",
      "photo": "/narsh2026/images/people/shawna.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "sidney-morehouse"
      ],
      "inferredParents": []
    },
    {
      "id": "greg-bennett",
      "name": "Greg Bennett",
      "photo": null,
      "groups": [
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-greg-bennett",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "leighanne-bennett",
      "name": "Leighanne Bennett",
      "photo": null,
      "groups": [
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-greg-bennett",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "gaurav-sandhar",
      "name": "Gaurav Sandhar",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "bill-chen",
      "name": "Bill Chen",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-angela-gu",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "fannette-hsin",
      "name": "Fannette Hsin",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "james-hageman",
      "name": "James Hageman",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-james-hageman",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "sarah-baird",
      "name": "Sarah Baird",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-james-hageman",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "sidney-morehouse",
      "name": "Sidney Morehouse",
      "photo": "/narsh2026/images/people/sid.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "shannon-noble",
      "name": "Shannon Noble",
      "photo": "/narsh2026/images/people/shannon.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-heather-morehouse",
      "side": "natalie",
      "parents": [
        "heather-morehouse"
      ],
      "inferredParents": []
    },
    {
      "id": "heather-morehouse",
      "name": "Heather Morehouse",
      "photo": "/narsh2026/images/people/heather.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-heather-morehouse",
      "side": "natalie",
      "parents": [
        "sidney-morehouse"
      ],
      "inferredParents": []
    },
    {
      "id": "james-noble",
      "name": "James Noble",
      "photo": "/narsh2026/images/people/james.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-heather-morehouse",
      "side": "natalie",
      "parents": [
        "heather-morehouse"
      ],
      "inferredParents": []
    },
    {
      "id": "karen-morehouse",
      "name": "Karen Morehouse",
      "photo": "/narsh2026/images/people/karen.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "sidney-morehouse"
      ],
      "inferredParents": []
    },
    {
      "id": "rosanne-fleury",
      "name": "Rosanne Fleury",
      "photo": "/narsh2026/images/people/rosanne.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gabrielle-blumer",
      "side": "natalie",
      "parents": [
        "mary-fleury"
      ],
      "inferredParents": []
    },
    {
      "id": "steve-blumer",
      "name": "Steve Blumer",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gabrielle-blumer",
      "side": "natalie",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "matt-dsouza",
      "name": "Matt D'Souza",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-grace-jean",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "grace-jean",
      "name": "Grace Jean",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-grace-jean",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "gaea-turman",
      "name": "Gaea Turman",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gaea-turman",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "daniel-prilik",
      "name": "Daniel Prilik",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "logan-howard",
      "name": "Logan Howard",
      "photo": null,
      "groups": [
        "stripe-coworkers"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-annie-huang",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "annie-huang",
      "name": "Annie Huang",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-annie-huang",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "teresa-solomon",
      "name": "Teresa Solomon",
      "photo": null,
      "groups": [
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-geoffrey-solomon",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "geoffrey-solomon",
      "name": "Geoffrey Solomon",
      "photo": null,
      "groups": [
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-geoffrey-solomon",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "emma-park",
      "name": "Emma Park",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-ayush-kapur",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "ayush-kapur",
      "name": "Ayush Kapur",
      "photo": null,
      "groups": [
        "waterloo",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-ayush-kapur",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "jason-lee",
      "name": "Jason Lee",
      "photo": null,
      "groups": [
        "meta-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "danielle-lavigne",
      "name": "Danielle Lavigne",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-brandon-lavigne",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "julia-lavigne",
      "name": "Julia Lavigne",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-brandon-lavigne",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "angela-gu",
      "name": "Angela Gu",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-angela-gu",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "rae-bennett",
      "name": "Rae Bennett",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "jasper-chapman-black",
      "name": "Jasper Chapman-Black",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-jasper-chapman-black",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "stacey-chapman-black",
      "name": "Stacey Chapman-Black",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-jasper-chapman-black",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "brandon-lavigne",
      "name": "Brandon Lavigne",
      "photo": null,
      "groups": [
        "meta-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-brandon-lavigne",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "chelsi-manhas",
      "name": "Chelsi Manhas",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-chelsi-manhas",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "svetomir-milanovic",
      "name": "Svetomir Milanovic",
      "photo": "/narsh2026/images/people/svetomir.jpeg",
      "groups": [
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-nicole-fleury",
      "side": "natalie",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "william-fleury",
      "name": "William Fleury",
      "photo": "/narsh2026/images/people/william.jpg",
      "groups": [
        "natalies-family",
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "mary-fleury"
      ],
      "inferredParents": []
    },
    {
      "id": "nicole-fleury",
      "name": "Nicole Fleury",
      "photo": "/narsh2026/images/people/nicole.jpg",
      "groups": [
        "natalies-family",
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-nicole-fleury",
      "side": "natalie",
      "parents": [
        "shawna-morehouse",
        "william-fleury"
      ],
      "inferredParents": []
    },
    {
      "id": "kyle-katchaluba",
      "name": "Kyle Katchaluba",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-chelsi-manhas",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "bradley-ramunas",
      "name": "Bradley Ramunas",
      "photo": null,
      "groups": [
        "stripe-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "natalie-tchokreff",
      "name": "Natalie Tchokreff",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-george-utsin",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "george-utsin",
      "name": "George Utsin",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-george-utsin",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "jonah-dlin",
      "name": "Jonah Dlin",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-dina-dlin",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "hannah-dobrik",
      "name": "Hannah Dobrik",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-hannah-dobrik",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "nariyan-krsnadas",
      "name": "Nariyan Krsnadas",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gaea-turman",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "ryan-drapeau",
      "name": "Ryan Drapeau",
      "photo": null,
      "groups": [
        "stripe-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "manjot-nagra",
      "name": "Manjot Nagra",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "spencer-dobrik",
      "name": "Spencer Dobrik",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-hannah-dobrik",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "sabrina-wasserman",
      "name": "Sabrina Wasserman",
      "photo": null,
      "groups": [
        "meta-coworkers",
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "dina-dlin",
      "name": "Dina Dlin",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-dina-dlin",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "stephen-melinyshyn",
      "name": "Stephen Melinyshyn",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-ashley-darton",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "ashley-darton",
      "name": "Ashley Darton",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-ashley-darton",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "claire-hsu",
      "name": "Claire Hsu",
      "photo": null,
      "groups": [
        "stripe-coworkers"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "shawna-huang",
      "name": "Shawna Huang",
      "photo": null,
      "groups": [
        "stripe-coworkers"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "isaac-madwed",
      "name": "Isaac Madwed",
      "photo": null,
      "groups": [
        "stripe-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-celine-rosak",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "brenda-morehouse",
      "name": "Brenda Morehouse",
      "photo": "/narsh2026/images/people/brenda.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "sidney-morehouse"
      ],
      "inferredParents": []
    },
    {
      "id": "alexandre-bondoux",
      "name": "Alexandre Bondoux",
      "photo": null,
      "groups": [
        "stripe-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "evan-morehouse",
      "name": "Evan Morehouse",
      "photo": "/narsh2026/images/people/evan.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "brenda-morehouse"
      ],
      "inferredParents": []
    },
    {
      "id": "celine-rosak",
      "name": "Celine Rosak",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-celine-rosak",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "sam-showalter",
      "name": "Sam Showalter",
      "photo": null,
      "groups": [
        "stripe-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-sam-showalter",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "david-mediati",
      "name": "David Mediati",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-christina-antinora",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "christina-antinora",
      "name": "Christina Antinora",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-christina-antinora",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "sarah-zhou",
      "name": "Sarah Zhou",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-sam-showalter",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "amy-hung",
      "name": "Amy Hung",
      "photo": null,
      "groups": [
        "stripe-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "maddie-hayman",
      "name": "Maddie Hayman",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "giao-nguyen",
      "name": "Giao Nguyen",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-giao-nguyen",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "tom-yang",
      "name": "Tom Yang",
      "photo": null,
      "groups": [
        "waterloo",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-giao-nguyen",
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "alex-hayman",
      "name": "Alex Hayman",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "shannan-young",
      "name": "Shannan Young",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "chantal-cossette",
      "name": "Chantal Cossette",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "david-lu",
      "name": "David Lu",
      "photo": null,
      "groups": [
        "meta-coworkers",
        "waterloo",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "anmol-mago",
      "name": "Anmol Mago",
      "photo": null,
      "groups": [
        "meta-coworkers",
        "waterloo",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "tiffany-yeung",
      "name": "Tiffany Yeung",
      "photo": null,
      "groups": [
        "waterloo",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "seth-hendrickson",
      "name": "Seth Hendrickson",
      "photo": null,
      "groups": [
        "stripe-coworkers"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "josh-jhinger",
      "name": "Josh Jhinger",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "nimret-malhi",
      "name": "Nimret Malhi",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "mary-fleury",
      "name": "Mary Fleury",
      "photo": "/narsh2026/images/people/mary.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "jatinder-kaur",
      "name": "Jatinder Kaur",
      "photo": "/narsh2026/images/people/jatinder.jpg",
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "jatinders-mom",
        "jatinders-dad"
      ],
      "inferredParents": []
    },
    {
      "id": "amritpal-rai",
      "name": "Amritpal Rai",
      "photo": "/narsh2026/images/people/amritpal.jpg",
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "balbir-rai"
      ],
      "inferredParents": []
    },
    {
      "id": "janessa-reimer",
      "name": "Janessa Reimer",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-glen-antle",
      "side": "natalie",
      "parents": [
        "glen-antle",
        "jennifer-reimer"
      ],
      "inferredParents": []
    },
    {
      "id": "guest",
      "name": "...",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "rene-fleury"
      ],
      "inferredParents": []
    },
    {
      "id": "aman-rai",
      "name": "Aman Rai",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-aman-rai",
      "side": "arash",
      "parents": [
        "gurpreet-rai",
        "kiran-kaur"
      ],
      "inferredParents": []
    },
    {
      "id": "amrit-kaur",
      "name": "Amrit Kaur",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-aman-rai",
      "side": "arash",
      "parents": [
        "amrits-mom",
        "amrits-dad"
      ],
      "inferredParents": []
    },
    {
      "id": "gurpreet-rai",
      "name": "Gurpreet Rai",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": "Taia",
      "householdId": "household-gurpreet-rai",
      "side": "arash",
      "parents": [
        "balbir-rai"
      ],
      "inferredParents": []
    },
    {
      "id": "kiran-kaur",
      "name": "Kiran Kaur",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": "Tai",
      "householdId": "household-gurpreet-rai",
      "side": "arash",
      "parents": [],
      "inferredParents": [
        "jasans-grandma",
        "jasans-grandpa"
      ]
    },
    {
      "id": "balbir-rai",
      "name": "Balbir Rai",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "mehreen-rai",
      "name": "Mehreen Rai",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "aman-rai",
        "amrit-kaur"
      ],
      "inferredParents": []
    },
    {
      "id": "nehmat-rai",
      "name": "Nehmat Rai",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "aman-rai",
        "amrit-kaur"
      ],
      "inferredParents": []
    },
    {
      "id": "rani-kaur",
      "name": "Rani Kaur",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "balbir-rai"
      ],
      "inferredParents": []
    },
    {
      "id": "harkanwal-rai",
      "name": "Harkanwal Rai",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-harkanwal-rai",
      "side": "arash",
      "parents": [
        "rani-kaur"
      ],
      "inferredParents": []
    },
    {
      "id": "upneet-bala",
      "name": "Upneet Bala",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "upneets-mom",
        "gurpreet-bala"
      ],
      "inferredParents": []
    },
    {
      "id": "upneets-mom",
      "name": "Upneet's mom",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gurpreet-bala",
      "side": "arash",
      "parents": [],
      "inferredParents": [
        "jasans-grandma",
        "jasans-grandpa"
      ]
    },
    {
      "id": "gurpreet-bala",
      "name": "Gurpreet Bala",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gurpreet-bala",
      "side": "arash",
      "parents": [
        "upneets-grandpa"
      ],
      "inferredParents": []
    },
    {
      "id": "jasjot-bala",
      "name": "Jasjot Bala",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "upneets-mom",
        "gurpreet-bala"
      ],
      "inferredParents": []
    },
    {
      "id": "upneets-grandpa",
      "name": "Upneet's grandpa (?)",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "navi-rai",
      "name": "Navi Rai",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "cookie-kaur",
        "kulwant-rai"
      ],
      "inferredParents": []
    },
    {
      "id": "gagan-rai",
      "name": "Gagan Rai",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "cookie-kaur",
        "kulwant-rai"
      ],
      "inferredParents": []
    },
    {
      "id": "cookie-kaur",
      "name": "Cookie Kaur",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-cookie-kaur",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "kulwant-rai",
      "name": "Kulwant Rai",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-cookie-kaur",
      "side": "arash",
      "parents": [
        "navis-grandpa",
        "navis-grandma"
      ],
      "inferredParents": []
    },
    {
      "id": "navis-grandpa",
      "name": "Navi's grandpa",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-navis-grandma",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "navis-grandma",
      "name": "Navi's grandma",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-navis-grandma",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "sira-auntie",
      "name": "Sira Auntie",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "ishas-grandpa",
        "ishas-grandma"
      ],
      "inferredParents": []
    },
    {
      "id": "isha-brar",
      "name": "Isha Brar",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "sira-auntie"
      ],
      "inferredParents": []
    },
    {
      "id": "ishas-grandpa",
      "name": "Isha's grandpa",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-ishas-grandma",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "ishas-grandma",
      "name": "Isha's grandma",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-ishas-grandma",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "shawn-brar",
      "name": "Shawn Brar",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "sira-auntie"
      ],
      "inferredParents": []
    },
    {
      "id": "shinday",
      "name": "Shinday",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-shinday",
      "side": "arash",
      "parents": [
        "ishas-grandpa",
        "ishas-grandma"
      ],
      "inferredParents": []
    },
    {
      "id": "shinday-kid-1",
      "name": "Shinday kid 1",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "shinday"
      ],
      "inferredParents": []
    },
    {
      "id": "shinday-kid-2",
      "name": "Shinday kid 2",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "shinday"
      ],
      "inferredParents": []
    },
    {
      "id": "shinday-kid-3",
      "name": "Shinday kid 3",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "shinday"
      ],
      "inferredParents": []
    },
    {
      "id": "shindays-husband",
      "name": "Shinday's husband",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-shinday",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "gurinder-khangura",
      "name": "Gurinder Khangura",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gurinder-khangura",
      "side": "arash",
      "parents": [
        "jasans-grandma",
        "jasans-grandpa"
      ],
      "inferredParents": []
    },
    {
      "id": "gurinders-wife",
      "name": "Gurinder's wife",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gurinder-khangura",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "jasan-khangura",
      "name": "Jasan Khangura",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "gurinder-khangura",
        "gurinders-wife"
      ],
      "inferredParents": []
    },
    {
      "id": "millen-khangura",
      "name": "Millen Khangura",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "gurinder-khangura",
        "gurinders-wife"
      ],
      "inferredParents": []
    },
    {
      "id": "jasans-grandma",
      "name": "Jasan's grandma",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-jasans-grandma",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "jasans-grandpa",
      "name": "Jasan's grandpa",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-jasans-grandma",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "aman",
      "name": "Aman",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "amrits-mom",
        "amrits-dad"
      ],
      "inferredParents": []
    },
    {
      "id": "gurleen",
      "name": "Gurleen",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "amrits-mom",
        "amrits-dad"
      ],
      "inferredParents": []
    },
    {
      "id": "amrits-mom",
      "name": "Amrit's mom",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-amrits-dad",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "amrits-dad",
      "name": "Amrit's dad",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-amrits-dad",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "harkanwals-wife",
      "name": "Harkanwal's wife",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-harkanwal-rai",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "gurnoor-boparai",
      "name": "Gurnoor Boparai",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "bhinda-boparai"
      ],
      "inferredParents": []
    },
    {
      "id": "bhinda-boparai",
      "name": "Bhinda Boparai",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": [
        "jatinders-mom",
        "jatinders-dad"
      ],
      "inferredParents": []
    },
    {
      "id": "jatinders-mom",
      "name": "Jatinder's mom",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-jatinders-dad",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    },
    {
      "id": "jatinders-dad",
      "name": "Jatinder's dad",
      "photo": null,
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-jatinders-dad",
      "side": "arash",
      "parents": [],
      "inferredParents": []
    }
  ];

  const EDGES = [
    {
      "source": "natalie",
      "target": "arash",
      "type": "couple"
    },
    {
      "source": "natalie",
      "target": "shawna-morehouse",
      "type": "parent"
    },
    {
      "source": "natalie",
      "target": "william-fleury",
      "type": "parent"
    },
    {
      "source": "arash",
      "target": "jatinder-kaur",
      "type": "parent"
    },
    {
      "source": "arash",
      "target": "amritpal-rai",
      "type": "parent"
    },
    {
      "source": "rene-fleury",
      "target": "mary-fleury",
      "type": "parent"
    },
    {
      "source": "katelyn-henry",
      "target": "guest",
      "type": "parent"
    },
    {
      "source": "natreisha-henry",
      "target": "guest",
      "type": "parent"
    },
    {
      "source": "kyle-francis",
      "target": "rosanne-fleury",
      "type": "parent"
    },
    {
      "source": "gabrielle-blumer",
      "target": "steve-blumer",
      "type": "parent"
    },
    {
      "source": "gabrielle-blumer",
      "target": "rosanne-fleury",
      "type": "parent"
    },
    {
      "source": "ben-blumer",
      "target": "steve-blumer",
      "type": "parent"
    },
    {
      "source": "jennifer-reimer",
      "target": "rene-fleury",
      "type": "parent"
    },
    {
      "source": "jillian-reimer",
      "target": "glen-antle",
      "type": "parent"
    },
    {
      "source": "jillian-reimer",
      "target": "jennifer-reimer",
      "type": "parent"
    },
    {
      "source": "shiloh-riddell",
      "target": "serenity-blumer",
      "type": "parent"
    },
    {
      "source": "taliah-riddell",
      "target": "serenity-blumer",
      "type": "parent"
    },
    {
      "source": "serenity-blumer",
      "target": "steve-blumer",
      "type": "parent"
    },
    {
      "source": "isaiah-riddell",
      "target": "serenity-blumer",
      "type": "parent"
    },
    {
      "source": "shawna-morehouse",
      "target": "sidney-morehouse",
      "type": "parent"
    },
    {
      "source": "shannon-noble",
      "target": "heather-morehouse",
      "type": "parent"
    },
    {
      "source": "heather-morehouse",
      "target": "sidney-morehouse",
      "type": "parent"
    },
    {
      "source": "james-noble",
      "target": "heather-morehouse",
      "type": "parent"
    },
    {
      "source": "karen-morehouse",
      "target": "sidney-morehouse",
      "type": "parent"
    },
    {
      "source": "rosanne-fleury",
      "target": "mary-fleury",
      "type": "parent"
    },
    {
      "source": "william-fleury",
      "target": "mary-fleury",
      "type": "parent"
    },
    {
      "source": "nicole-fleury",
      "target": "shawna-morehouse",
      "type": "parent"
    },
    {
      "source": "nicole-fleury",
      "target": "william-fleury",
      "type": "parent"
    },
    {
      "source": "brenda-morehouse",
      "target": "sidney-morehouse",
      "type": "parent"
    },
    {
      "source": "evan-morehouse",
      "target": "brenda-morehouse",
      "type": "parent"
    },
    {
      "source": "jatinder-kaur",
      "target": "jatinders-mom",
      "type": "parent"
    },
    {
      "source": "jatinder-kaur",
      "target": "jatinders-dad",
      "type": "parent"
    },
    {
      "source": "amritpal-rai",
      "target": "balbir-rai",
      "type": "parent"
    },
    {
      "source": "janessa-reimer",
      "target": "glen-antle",
      "type": "parent"
    },
    {
      "source": "janessa-reimer",
      "target": "jennifer-reimer",
      "type": "parent"
    },
    {
      "source": "guest",
      "target": "rene-fleury",
      "type": "parent"
    },
    {
      "source": "aman-rai",
      "target": "gurpreet-rai",
      "type": "parent"
    },
    {
      "source": "aman-rai",
      "target": "kiran-kaur",
      "type": "parent"
    },
    {
      "source": "amrit-kaur",
      "target": "amrits-mom",
      "type": "parent"
    },
    {
      "source": "amrit-kaur",
      "target": "amrits-dad",
      "type": "parent"
    },
    {
      "source": "gurpreet-rai",
      "target": "balbir-rai",
      "type": "parent"
    },
    {
      "source": "mehreen-rai",
      "target": "aman-rai",
      "type": "parent"
    },
    {
      "source": "mehreen-rai",
      "target": "amrit-kaur",
      "type": "parent"
    },
    {
      "source": "nehmat-rai",
      "target": "aman-rai",
      "type": "parent"
    },
    {
      "source": "nehmat-rai",
      "target": "amrit-kaur",
      "type": "parent"
    },
    {
      "source": "rani-kaur",
      "target": "balbir-rai",
      "type": "parent"
    },
    {
      "source": "harkanwal-rai",
      "target": "rani-kaur",
      "type": "parent"
    },
    {
      "source": "upneet-bala",
      "target": "upneets-mom",
      "type": "parent"
    },
    {
      "source": "upneet-bala",
      "target": "gurpreet-bala",
      "type": "parent"
    },
    {
      "source": "gurpreet-bala",
      "target": "upneets-grandpa",
      "type": "parent"
    },
    {
      "source": "jasjot-bala",
      "target": "upneets-mom",
      "type": "parent"
    },
    {
      "source": "jasjot-bala",
      "target": "gurpreet-bala",
      "type": "parent"
    },
    {
      "source": "navi-rai",
      "target": "cookie-kaur",
      "type": "parent"
    },
    {
      "source": "navi-rai",
      "target": "kulwant-rai",
      "type": "parent"
    },
    {
      "source": "gagan-rai",
      "target": "cookie-kaur",
      "type": "parent"
    },
    {
      "source": "gagan-rai",
      "target": "kulwant-rai",
      "type": "parent"
    },
    {
      "source": "kulwant-rai",
      "target": "navis-grandpa",
      "type": "parent"
    },
    {
      "source": "kulwant-rai",
      "target": "navis-grandma",
      "type": "parent"
    },
    {
      "source": "sira-auntie",
      "target": "ishas-grandpa",
      "type": "parent"
    },
    {
      "source": "sira-auntie",
      "target": "ishas-grandma",
      "type": "parent"
    },
    {
      "source": "isha-brar",
      "target": "sira-auntie",
      "type": "parent"
    },
    {
      "source": "shawn-brar",
      "target": "sira-auntie",
      "type": "parent"
    },
    {
      "source": "shinday",
      "target": "ishas-grandpa",
      "type": "parent"
    },
    {
      "source": "shinday",
      "target": "ishas-grandma",
      "type": "parent"
    },
    {
      "source": "shinday-kid-1",
      "target": "shinday",
      "type": "parent"
    },
    {
      "source": "shinday-kid-2",
      "target": "shinday",
      "type": "parent"
    },
    {
      "source": "shinday-kid-3",
      "target": "shinday",
      "type": "parent"
    },
    {
      "source": "gurinder-khangura",
      "target": "jasans-grandma",
      "type": "parent"
    },
    {
      "source": "gurinder-khangura",
      "target": "jasans-grandpa",
      "type": "parent"
    },
    {
      "source": "jasan-khangura",
      "target": "gurinder-khangura",
      "type": "parent"
    },
    {
      "source": "jasan-khangura",
      "target": "gurinders-wife",
      "type": "parent"
    },
    {
      "source": "millen-khangura",
      "target": "gurinder-khangura",
      "type": "parent"
    },
    {
      "source": "millen-khangura",
      "target": "gurinders-wife",
      "type": "parent"
    },
    {
      "source": "aman",
      "target": "amrits-mom",
      "type": "parent"
    },
    {
      "source": "aman",
      "target": "amrits-dad",
      "type": "parent"
    },
    {
      "source": "gurleen",
      "target": "amrits-mom",
      "type": "parent"
    },
    {
      "source": "gurleen",
      "target": "amrits-dad",
      "type": "parent"
    },
    {
      "source": "gurnoor-boparai",
      "target": "bhinda-boparai",
      "type": "parent"
    },
    {
      "source": "bhinda-boparai",
      "target": "jatinders-mom",
      "type": "parent"
    },
    {
      "source": "bhinda-boparai",
      "target": "jatinders-dad",
      "type": "parent"
    },
    {
      "source": "natalie",
      "target": "nicole-fleury",
      "type": "sibling"
    },
    {
      "source": "rene-fleury",
      "target": "rosanne-fleury",
      "type": "sibling"
    },
    {
      "source": "rene-fleury",
      "target": "william-fleury",
      "type": "sibling"
    },
    {
      "source": "rosanne-fleury",
      "target": "william-fleury",
      "type": "sibling"
    },
    {
      "source": "katelyn-henry",
      "target": "natreisha-henry",
      "type": "sibling"
    },
    {
      "source": "kyle-francis",
      "target": "gabrielle-blumer",
      "type": "sibling"
    },
    {
      "source": "gabrielle-blumer",
      "target": "ben-blumer",
      "type": "sibling"
    },
    {
      "source": "gabrielle-blumer",
      "target": "serenity-blumer",
      "type": "sibling"
    },
    {
      "source": "ben-blumer",
      "target": "serenity-blumer",
      "type": "sibling"
    },
    {
      "source": "jennifer-reimer",
      "target": "guest",
      "type": "sibling"
    },
    {
      "source": "jillian-reimer",
      "target": "janessa-reimer",
      "type": "sibling"
    },
    {
      "source": "shiloh-riddell",
      "target": "taliah-riddell",
      "type": "sibling"
    },
    {
      "source": "shiloh-riddell",
      "target": "isaiah-riddell",
      "type": "sibling"
    },
    {
      "source": "taliah-riddell",
      "target": "isaiah-riddell",
      "type": "sibling"
    },
    {
      "source": "shawna-morehouse",
      "target": "heather-morehouse",
      "type": "sibling"
    },
    {
      "source": "shawna-morehouse",
      "target": "karen-morehouse",
      "type": "sibling"
    },
    {
      "source": "shawna-morehouse",
      "target": "brenda-morehouse",
      "type": "sibling"
    },
    {
      "source": "heather-morehouse",
      "target": "karen-morehouse",
      "type": "sibling"
    },
    {
      "source": "heather-morehouse",
      "target": "brenda-morehouse",
      "type": "sibling"
    },
    {
      "source": "karen-morehouse",
      "target": "brenda-morehouse",
      "type": "sibling"
    },
    {
      "source": "shannon-noble",
      "target": "james-noble",
      "type": "sibling"
    },
    {
      "source": "jatinder-kaur",
      "target": "bhinda-boparai",
      "type": "sibling"
    },
    {
      "source": "amritpal-rai",
      "target": "gurpreet-rai",
      "type": "sibling"
    },
    {
      "source": "amritpal-rai",
      "target": "rani-kaur",
      "type": "sibling"
    },
    {
      "source": "gurpreet-rai",
      "target": "rani-kaur",
      "type": "sibling"
    },
    {
      "source": "amrit-kaur",
      "target": "aman",
      "type": "sibling"
    },
    {
      "source": "amrit-kaur",
      "target": "gurleen",
      "type": "sibling"
    },
    {
      "source": "aman",
      "target": "gurleen",
      "type": "sibling"
    },
    {
      "source": "mehreen-rai",
      "target": "nehmat-rai",
      "type": "sibling"
    },
    {
      "source": "upneet-bala",
      "target": "jasjot-bala",
      "type": "sibling"
    },
    {
      "source": "navi-rai",
      "target": "gagan-rai",
      "type": "sibling"
    },
    {
      "source": "sira-auntie",
      "target": "shinday",
      "type": "sibling"
    },
    {
      "source": "isha-brar",
      "target": "shawn-brar",
      "type": "sibling"
    },
    {
      "source": "shinday-kid-1",
      "target": "shinday-kid-2",
      "type": "sibling"
    },
    {
      "source": "shinday-kid-1",
      "target": "shinday-kid-3",
      "type": "sibling"
    },
    {
      "source": "shinday-kid-2",
      "target": "shinday-kid-3",
      "type": "sibling"
    },
    {
      "source": "jasan-khangura",
      "target": "millen-khangura",
      "type": "sibling"
    },
    {
      "source": "kiran-kaur",
      "target": "upneets-mom",
      "type": "sibling"
    },
    {
      "source": "kiran-kaur",
      "target": "gurinder-khangura",
      "type": "sibling"
    },
    {
      "source": "upneets-mom",
      "target": "gurinder-khangura",
      "type": "sibling"
    },
    {
      "source": "balbir-rai",
      "target": "navis-grandpa",
      "type": "sibling"
    },
    {
      "source": "balbir-rai",
      "target": "ishas-grandpa",
      "type": "sibling"
    },
    {
      "source": "navis-grandpa",
      "target": "ishas-grandpa",
      "type": "sibling"
    }
  ];

  const HOUSEHOLDS = [
    {
      "id": "household-cindy-fleury",
      "members": [
        "cindy-fleury",
        "rene-fleury"
      ],
      "displayName": "Cindy & Rene"
    },
    {
      "id": "household-katelyn-henry",
      "members": [
        "katelyn-henry",
        "natreisha-henry"
      ],
      "displayName": "Katelyn & Natreisha"
    },
    {
      "id": "household-kendra-kusick",
      "members": [
        "kyle-francis",
        "kendra-kusick"
      ],
      "displayName": "Kyle & Kendra"
    },
    {
      "id": "household-gabrielle-blumer",
      "members": [
        "gabrielle-blumer",
        "rosanne-fleury",
        "steve-blumer"
      ],
      "displayName": "Gabrielle, Rosanne & Steve"
    },
    {
      "id": "household-glen-antle",
      "members": [
        "jennifer-reimer",
        "glen-antle",
        "jillian-reimer",
        "janessa-reimer"
      ],
      "displayName": "Jennifer, Glen, Jillian & Janessa"
    },
    {
      "id": "household-isaiah-riddell",
      "members": [
        "shiloh-riddell",
        "taliah-riddell",
        "serenity-blumer",
        "isaiah-riddell"
      ],
      "displayName": "Shiloh, Taliah, Serenity & Isaiah"
    },
    {
      "id": "household-farzad-sangi",
      "members": [
        "sumita-barahmand",
        "farzad-sangi"
      ],
      "displayName": "Sumita & Farzad"
    },
    {
      "id": "household-georgia-hong",
      "members": [
        "jerry-liu",
        "georgia-hong"
      ],
      "displayName": "Jerry & Georgia"
    },
    {
      "id": "household-amy-qiu",
      "members": [
        "amy-qiu",
        "phillip-vo"
      ],
      "displayName": "Amy & Phillip"
    },
    {
      "id": "household-greg-bennett",
      "members": [
        "greg-bennett",
        "leighanne-bennett"
      ],
      "displayName": "Greg & Leighanne"
    },
    {
      "id": "household-angela-gu",
      "members": [
        "bill-chen",
        "angela-gu"
      ],
      "displayName": "Bill & Angela"
    },
    {
      "id": "household-james-hageman",
      "members": [
        "james-hageman",
        "sarah-baird"
      ],
      "displayName": "James & Sarah"
    },
    {
      "id": "household-heather-morehouse",
      "members": [
        "shannon-noble",
        "heather-morehouse",
        "james-noble"
      ],
      "displayName": "Shannon, Heather & James"
    },
    {
      "id": "household-grace-jean",
      "members": [
        "matt-dsouza",
        "grace-jean"
      ],
      "displayName": "Matt & Grace"
    },
    {
      "id": "household-gaea-turman",
      "members": [
        "gaea-turman",
        "nariyan-krsnadas"
      ],
      "displayName": "Gaea & Nariyan"
    },
    {
      "id": "household-annie-huang",
      "members": [
        "logan-howard",
        "annie-huang"
      ],
      "displayName": "Logan & Annie"
    },
    {
      "id": "household-geoffrey-solomon",
      "members": [
        "teresa-solomon",
        "geoffrey-solomon"
      ],
      "displayName": "Teresa & Geoffrey"
    },
    {
      "id": "household-ayush-kapur",
      "members": [
        "emma-park",
        "ayush-kapur"
      ],
      "displayName": "Emma & Ayush"
    },
    {
      "id": "household-brandon-lavigne",
      "members": [
        "danielle-lavigne",
        "julia-lavigne",
        "brandon-lavigne"
      ],
      "displayName": "Danielle, Julia & Brandon"
    },
    {
      "id": "household-jasper-chapman-black",
      "members": [
        "jasper-chapman-black",
        "stacey-chapman-black"
      ],
      "displayName": "Jasper & Stacey"
    },
    {
      "id": "household-chelsi-manhas",
      "members": [
        "chelsi-manhas",
        "kyle-katchaluba"
      ],
      "displayName": "Chelsi & Kyle"
    },
    {
      "id": "household-nicole-fleury",
      "members": [
        "svetomir-milanovic",
        "nicole-fleury"
      ],
      "displayName": "Svetomir & Nicole"
    },
    {
      "id": "household-george-utsin",
      "members": [
        "natalie-tchokreff",
        "george-utsin"
      ],
      "displayName": "Natalie & George"
    },
    {
      "id": "household-dina-dlin",
      "members": [
        "jonah-dlin",
        "dina-dlin"
      ],
      "displayName": "Jonah & Dina"
    },
    {
      "id": "household-hannah-dobrik",
      "members": [
        "hannah-dobrik",
        "spencer-dobrik"
      ],
      "displayName": "Hannah & Spencer"
    },
    {
      "id": "household-ashley-darton",
      "members": [
        "stephen-melinyshyn",
        "ashley-darton"
      ],
      "displayName": "Stephen & Ashley"
    },
    {
      "id": "household-celine-rosak",
      "members": [
        "isaac-madwed",
        "celine-rosak"
      ],
      "displayName": "Isaac & Celine"
    },
    {
      "id": "household-sam-showalter",
      "members": [
        "sam-showalter",
        "sarah-zhou"
      ],
      "displayName": "Sam & Sarah"
    },
    {
      "id": "household-christina-antinora",
      "members": [
        "david-mediati",
        "christina-antinora"
      ],
      "displayName": "David & Christina"
    },
    {
      "id": "household-giao-nguyen",
      "members": [
        "giao-nguyen",
        "tom-yang"
      ],
      "displayName": "Giao & Tom"
    },
    {
      "id": "household-aman-rai",
      "members": [
        "aman-rai",
        "amrit-kaur"
      ],
      "displayName": "Aman & Amrit"
    },
    {
      "id": "household-gurpreet-rai",
      "members": [
        "gurpreet-rai",
        "kiran-kaur"
      ],
      "displayName": "Gurpreet & Kiran"
    },
    {
      "id": "household-harkanwal-rai",
      "members": [
        "harkanwal-rai",
        "harkanwals-wife"
      ],
      "displayName": "Harkanwal & Harkanwal's"
    },
    {
      "id": "household-gurpreet-bala",
      "members": [
        "upneets-mom",
        "gurpreet-bala"
      ],
      "displayName": "Upneet's & Gurpreet"
    },
    {
      "id": "household-cookie-kaur",
      "members": [
        "cookie-kaur",
        "kulwant-rai"
      ],
      "displayName": "Cookie & Kulwant"
    },
    {
      "id": "household-navis-grandma",
      "members": [
        "navis-grandpa",
        "navis-grandma"
      ],
      "displayName": "Navi's & Navi's"
    },
    {
      "id": "household-ishas-grandma",
      "members": [
        "ishas-grandpa",
        "ishas-grandma"
      ],
      "displayName": "Isha's & Isha's"
    },
    {
      "id": "household-shinday",
      "members": [
        "shinday",
        "shindays-husband"
      ],
      "displayName": "Shinday & Shinday's"
    },
    {
      "id": "household-gurinder-khangura",
      "members": [
        "gurinder-khangura",
        "gurinders-wife"
      ],
      "displayName": "Gurinder & Gurinder's"
    },
    {
      "id": "household-jasans-grandma",
      "members": [
        "jasans-grandma",
        "jasans-grandpa"
      ],
      "displayName": "Jasan's & Jasan's"
    },
    {
      "id": "household-amrits-dad",
      "members": [
        "amrits-mom",
        "amrits-dad"
      ],
      "displayName": "Amrit's & Amrit's"
    },
    {
      "id": "household-jatinders-dad",
      "members": [
        "jatinders-mom",
        "jatinders-dad"
      ],
      "displayName": "Jatinder's & Jatinder's"
    }
  ];

  const MARRIAGES = [
    {
      "a": "shawna-morehouse",
      "b": "william-fleury",
      "side": "natalie"
    },
    {
      "a": "amritpal-rai",
      "b": "jatinder-kaur",
      "side": "arash"
    },
    {
      "a": "rosanne-fleury",
      "b": "steve-blumer",
      "side": "natalie"
    },
    {
      "a": "glen-antle",
      "b": "jennifer-reimer",
      "side": "natalie"
    },
    {
      "a": "jatinders-dad",
      "b": "jatinders-mom",
      "side": "arash"
    },
    {
      "a": "gurpreet-rai",
      "b": "kiran-kaur",
      "side": "arash"
    },
    {
      "a": "amrits-dad",
      "b": "amrits-mom",
      "side": "arash"
    },
    {
      "a": "aman-rai",
      "b": "amrit-kaur",
      "side": "arash"
    },
    {
      "a": "gurpreet-bala",
      "b": "upneets-mom",
      "side": "arash"
    },
    {
      "a": "cookie-kaur",
      "b": "kulwant-rai",
      "side": "arash"
    },
    {
      "a": "navis-grandma",
      "b": "navis-grandpa",
      "side": "arash"
    },
    {
      "a": "ishas-grandma",
      "b": "ishas-grandpa",
      "side": "arash"
    },
    {
      "a": "jasans-grandma",
      "b": "jasans-grandpa",
      "side": "arash"
    },
    {
      "a": "gurinder-khangura",
      "b": "gurinders-wife",
      "side": "arash"
    },
    {
      "a": "cindy-fleury",
      "b": "rene-fleury",
      "side": "natalie"
    },
    {
      "a": "farzad-sangi",
      "b": "sumita-barahmand",
      "side": null
    },
    {
      "a": "georgia-hong",
      "b": "jerry-liu",
      "side": null
    },
    {
      "a": "kendra-kusick",
      "b": "kyle-francis",
      "side": "natalie"
    },
    {
      "a": "amy-qiu",
      "b": "phillip-vo",
      "side": null
    },
    {
      "a": "greg-bennett",
      "b": "leighanne-bennett",
      "side": null
    },
    {
      "a": "james-hageman",
      "b": "sarah-baird",
      "side": null
    },
    {
      "a": "grace-jean",
      "b": "matt-dsouza",
      "side": null
    },
    {
      "a": "gaea-turman",
      "b": "nariyan-krsnadas",
      "side": null
    },
    {
      "a": "annie-huang",
      "b": "logan-howard",
      "side": null
    },
    {
      "a": "geoffrey-solomon",
      "b": "teresa-solomon",
      "side": null
    },
    {
      "a": "ayush-kapur",
      "b": "emma-park",
      "side": null
    },
    {
      "a": "brandon-lavigne",
      "b": "danielle-lavigne",
      "side": null
    },
    {
      "a": "brandon-lavigne",
      "b": "julia-lavigne",
      "side": null
    },
    {
      "a": "angela-gu",
      "b": "bill-chen",
      "side": null
    },
    {
      "a": "jasper-chapman-black",
      "b": "stacey-chapman-black",
      "side": null
    },
    {
      "a": "chelsi-manhas",
      "b": "kyle-katchaluba",
      "side": null
    },
    {
      "a": "nicole-fleury",
      "b": "svetomir-milanovic",
      "side": "natalie"
    },
    {
      "a": "george-utsin",
      "b": "natalie-tchokreff",
      "side": null
    },
    {
      "a": "hannah-dobrik",
      "b": "spencer-dobrik",
      "side": null
    },
    {
      "a": "dina-dlin",
      "b": "jonah-dlin",
      "side": null
    },
    {
      "a": "ashley-darton",
      "b": "stephen-melinyshyn",
      "side": null
    },
    {
      "a": "celine-rosak",
      "b": "isaac-madwed",
      "side": null
    },
    {
      "a": "christina-antinora",
      "b": "david-mediati",
      "side": null
    },
    {
      "a": "sam-showalter",
      "b": "sarah-zhou",
      "side": null
    },
    {
      "a": "giao-nguyen",
      "b": "tom-yang",
      "side": null
    },
    {
      "a": "shinday",
      "b": "shindays-husband",
      "side": "arash"
    },
    {
      "a": "harkanwal-rai",
      "b": "harkanwals-wife",
      "side": "arash"
    }
  ];

  const SIBLING_GROUPS = [
    [
      "kiran-kaur",
      "upneets-mom",
      "gurinder-khangura"
    ],
    [
      "balbir-rai",
      "navis-grandpa",
      "ishas-grandpa"
    ]
  ];

  const getGuestById = (id) => GUESTS.find(g => g.id === id) || null;
  const getGuestsByGroup = (groupId) => GUESTS.filter(g => g.groups.includes(groupId));
  const getGuestsByCity = (cityId) => GUESTS.filter(g => g.cities.includes(cityId));
  const searchGuests = (query) => {
    const q = query.trim().toLowerCase();
    if (!q) return [];
    return GUESTS.filter(g => g.name.toLowerCase().includes(q));
  };

  const getSocialNodes = () => {
    const householdMap = new Map();
    HOUSEHOLDS.forEach(h => { h.members.forEach(m => householdMap.set(m, h)); });
    const processed = new Set();
    const socialNodes = [];
    GUESTS.forEach(guest => {
      if (processed.has(guest.id)) return;
      const household = householdMap.get(guest.id);
      if (household) {
        household.members.forEach(m => processed.add(m));
        const members = household.members.map(m => getGuestById(m)).filter(Boolean);
        const allGroups = [...new Set(members.flatMap(m => m.groups))];
        const allCities = [...new Set(members.flatMap(m => m.cities))];
        // Distinct member photos: two people with different photos show both
        // (split node); if members share one photo file they're pictured
        // together, so it dedupes to a single photo.
        const photos = [...new Set(members.map(m => m.photo).filter(Boolean))];
        const photo = photos[0] || null;
        const isCouple = members.some(m => m.isCouple);
        socialNodes.push({
          id: household.id, name: household.displayName, photo, photos,
          groups: allGroups, cities: allCities, isCouple,
          memberIds: household.members, isHousehold: true
        });
      } else {
        processed.add(guest.id);
        socialNodes.push({
          id: guest.id, name: guest.name, photo: guest.photo,
          photos: guest.photo ? [guest.photo] : [],
          groups: guest.groups, cities: guest.cities, isCouple: guest.isCouple,
          memberIds: [guest.id], isHousehold: false
        });
      }
    });
    return socialNodes;
  };

  const getSocialEdges = (socialNodes) => {
    const nodeIdSet = new Set(socialNodes.map(n => n.id));
    const memberToNodeId = new Map();
    socialNodes.forEach(n => { n.memberIds.forEach(m => memberToNodeId.set(m, n.id)); });
    const edgeSet = new Set();
    const remapped = [];
    EDGES.forEach(edge => {
      const sourceId = memberToNodeId.get(edge.source) || edge.source;
      const targetId = memberToNodeId.get(edge.target) || edge.target;
      if (sourceId === targetId) return;
      if (!nodeIdSet.has(sourceId) || !nodeIdSet.has(targetId)) return;
      const key = [sourceId, targetId].sort().join("--");
      if (edgeSet.has(key)) return;
      edgeSet.add(key);
      remapped.push({ source: sourceId, target: targetId, type: edge.type });
    });
    return remapped;
  };

  return {
    GROUPS, CITIES, GUESTS, EDGES, HOUSEHOLDS, MARRIAGES, SIBLING_GROUPS,
    getGuestById, getGuestsByGroup, getGuestsByCity, searchGuests,
    getSocialNodes, getSocialEdges
  };
})();
