// Narsh 2026 — Guest Data Module
// AUTO-GENERATED by build-guests.js from guests.csv — do not edit by hand.
// To change guests, edit guests.csv and re-run: node narsh2026/our-people/build-guests.js

const NARSH_GUESTS = (() => {
  "use strict";

  const GROUPS = [
    {
      "id": "natalies-family",
      "label": "Natalie's Family",
      "color": "#D4A843"
    },
    {
      "id": "arashs-family",
      "label": "Arash's Family",
      "color": "#2A9D8F"
    },
    {
      "id": "meta-coworkers",
      "label": "Meta Coworkers",
      "color": "#C2704F"
    },
    {
      "id": "seattleite",
      "label": "Seattleite",
      "color": "#6B8E9E"
    },
    {
      "id": "waterloo",
      "label": "Waterloo",
      "color": "#A8763E"
    },
    {
      "id": "cayman-crew",
      "label": "Cayman Crew",
      "color": "#C9928E"
    },
    {
      "id": "abby-friends",
      "label": "Abby Friends",
      "color": "#B07D62"
    },
    {
      "id": "stripe-coworkers",
      "label": "Stripe Coworkers",
      "color": "#8E7CC3"
    }
  ];

  const CITIES = [
    {
      "id": "seattle",
      "label": "Seattle"
    },
    {
      "id": "grand-cayman",
      "label": "Grand Cayman"
    },
    {
      "id": "waterloo",
      "label": "Waterloo"
    },
    {
      "id": "mumbai",
      "label": "Mumbai"
    },
    {
      "id": "auckland",
      "label": "Auckland"
    }
  ];

  const GUESTS = [
    {
      "id": "natalie",
      "name": "Natalie Fleury",
      "photo": "/narsh2026/images/people/natalie.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [
        "seattle",
        "grand-cayman",
        "waterloo"
      ],
      "isCouple": true,
      "funFact": "Can name every iguana species native to the Cayman Islands.",
      "connectionToCouple": "The couple (you two!)",
      "householdId": null,
      "side": "natalie",
      "parents": [
        "shawna-morehouse",
        "william-fleury"
      ]
    },
    {
      "id": "arash",
      "name": "Arash Rai",
      "photo": "/narsh2026/images/people/arash.jpg",
      "groups": [
        "arashs-family"
      ],
      "cities": [
        "seattle",
        "mumbai",
        "auckland",
        "waterloo"
      ],
      "isCouple": true,
      "funFact": "Has lived on four continents before turning twenty.",
      "connectionToCouple": "The couple (you two!)",
      "householdId": null,
      "side": "arash",
      "parents": [
        "jatinder-kaur",
        "amritpal-rai"
      ]
    },
    {
      "id": "cindy-fleury",
      "name": "Cindy Fleury",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-cindy-fleury",
      "side": "natalie",
      "parents": []
    },
    {
      "id": "rene-fleury",
      "name": "Rene Fleury",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-cindy-fleury",
      "side": "natalie",
      "parents": [
        "mary-fleury"
      ]
    },
    {
      "id": "katelyn-henry",
      "name": "Katelyn Henry",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-katelyn-henry",
      "side": "natalie",
      "parents": [
        "rene-fleury"
      ]
    },
    {
      "id": "natreisha-henry",
      "name": "Natreisha Henry",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-katelyn-henry",
      "side": "natalie",
      "parents": [
        "rene-fleury"
      ]
    },
    {
      "id": "ben-blumer",
      "name": "Ben Blumer",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "steve-blumer"
      ]
    },
    {
      "id": "jennifer-reimer",
      "name": "Jennifer Reimer",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-glen-antle",
      "side": "natalie",
      "parents": [
        "rene-fleury"
      ]
    },
    {
      "id": "glen-antle",
      "name": "Glen Antle",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-glen-antle",
      "side": "natalie",
      "parents": []
    },
    {
      "id": "jillian-reimer",
      "name": "Jillian Reimer",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-glen-antle",
      "side": "natalie",
      "parents": [
        "glen-antle",
        "jennifer-reimer"
      ]
    },
    {
      "id": "shiloh-riddell",
      "name": "Shiloh Riddell",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-isaiah-riddell",
      "side": "natalie",
      "parents": [
        "serenity-blumer"
      ]
    },
    {
      "id": "taliah-riddell",
      "name": "Taliah Riddell",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-isaiah-riddell",
      "side": "natalie",
      "parents": [
        "serenity-blumer"
      ]
    },
    {
      "id": "serenity-blumer",
      "name": "Serenity Blumer",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-isaiah-riddell",
      "side": "natalie",
      "parents": [
        "steve-blumer"
      ]
    },
    {
      "id": "isaiah-riddell",
      "name": "Isaiah Riddell",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-isaiah-riddell",
      "side": "natalie",
      "parents": [
        "serenity-blumer"
      ]
    },
    {
      "id": "sumita-barahmand",
      "name": "Sumita Barahmand",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-farzad-sangi",
      "side": null,
      "parents": []
    },
    {
      "id": "farzad-sangi",
      "name": "Farzad Sangi",
      "photo": null,
      "groups": [
        "meta-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-farzad-sangi",
      "side": null,
      "parents": []
    },
    {
      "id": "susan-macrae",
      "name": "Susan MacRae",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "jerry-liu",
      "name": "Jerry Liu",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-georgia-hong",
      "side": null,
      "parents": []
    },
    {
      "id": "georgia-hong",
      "name": "Georgia Hong",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-georgia-hong",
      "side": null,
      "parents": []
    },
    {
      "id": "kendra-kusick",
      "name": "Kendra Kusick",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-kendra-kusick",
      "side": "natalie",
      "parents": []
    },
    {
      "id": "amy-qiu",
      "name": "Amy Qiu",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-amy-qiu",
      "side": null,
      "parents": []
    },
    {
      "id": "phillip-vo",
      "name": "Phillip Vo",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-amy-qiu",
      "side": null,
      "parents": []
    },
    {
      "id": "shawna-morehouse",
      "name": "Shawna Morehouse",
      "photo": "/narsh2026/images/people/shawna.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "sidney-morehouse"
      ]
    },
    {
      "id": "greg-bennett",
      "name": "Greg Bennett",
      "photo": null,
      "groups": [
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-greg-bennett",
      "side": null,
      "parents": []
    },
    {
      "id": "leighanne-bennett",
      "name": "Leighanne Bennett",
      "photo": null,
      "groups": [
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-greg-bennett",
      "side": null,
      "parents": []
    },
    {
      "id": "gaurav-sandhar",
      "name": "Gaurav Sandhar",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "bill-chen",
      "name": "Bill Chen",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-angela-gu",
      "side": null,
      "parents": []
    },
    {
      "id": "fannette-hsin",
      "name": "Fannette Hsin",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "james-hageman",
      "name": "James Hageman",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-james-hageman",
      "side": null,
      "parents": []
    },
    {
      "id": "sarah-baird",
      "name": "Sarah Baird",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-james-hageman",
      "side": null,
      "parents": []
    },
    {
      "id": "sidney-morehouse",
      "name": "Sidney Morehouse",
      "photo": "/narsh2026/images/people/sid.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": []
    },
    {
      "id": "shannon-noble",
      "name": "Shannon Noble",
      "photo": "/narsh2026/images/people/shannon.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-heather-morehouse",
      "side": "natalie",
      "parents": [
        "heather-morehouse"
      ]
    },
    {
      "id": "heather-morehouse",
      "name": "Heather Morehouse",
      "photo": "/narsh2026/images/people/heather.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-heather-morehouse",
      "side": "natalie",
      "parents": [
        "sidney-morehouse"
      ]
    },
    {
      "id": "james-noble",
      "name": "James Noble",
      "photo": "/narsh2026/images/people/james.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-heather-morehouse",
      "side": "natalie",
      "parents": [
        "heather-morehouse"
      ]
    },
    {
      "id": "karen-morehouse",
      "name": "Karen Morehouse",
      "photo": "/narsh2026/images/people/karen.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "sidney-morehouse"
      ]
    },
    {
      "id": "rosanne-fleury",
      "name": "Rosanne Fleury",
      "photo": "/narsh2026/images/people/rosanne.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gabrielle-blumer",
      "side": "natalie",
      "parents": [
        "mary-fleury"
      ]
    },
    {
      "id": "steve-blumer",
      "name": "Steve Blumer",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gabrielle-blumer",
      "side": "natalie",
      "parents": []
    },
    {
      "id": "matt-dsouza",
      "name": "Matt D'Souza",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-grace-jean",
      "side": null,
      "parents": []
    },
    {
      "id": "gabrielle-blumer",
      "name": "Gabrielle Blumer",
      "photo": "/narsh2026/images/people/gabrielle.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gabrielle-blumer",
      "side": "natalie",
      "parents": [
        "steve-blumer",
        "rosanne-fleury"
      ]
    },
    {
      "id": "grace-jean",
      "name": "Grace Jean",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-grace-jean",
      "side": null,
      "parents": []
    },
    {
      "id": "gaea-turman",
      "name": "Gaea Turman",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gaea-turman",
      "side": null,
      "parents": []
    },
    {
      "id": "daniel-prilik",
      "name": "Daniel Prilik",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "logan-howard",
      "name": "Logan Howard",
      "photo": null,
      "groups": [
        "stripe-coworkers"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-annie-huang",
      "side": null,
      "parents": []
    },
    {
      "id": "annie-huang",
      "name": "Annie Huang",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-annie-huang",
      "side": null,
      "parents": []
    },
    {
      "id": "teresa-solomon",
      "name": "Teresa Solomon",
      "photo": null,
      "groups": [
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-geoffrey-solomon",
      "side": null,
      "parents": []
    },
    {
      "id": "geoffrey-solomon",
      "name": "Geoffrey Solomon",
      "photo": null,
      "groups": [
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-geoffrey-solomon",
      "side": null,
      "parents": []
    },
    {
      "id": "emma-park",
      "name": "Emma Park",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-ayush-kapur",
      "side": null,
      "parents": []
    },
    {
      "id": "ayush-kapur",
      "name": "Ayush Kapur",
      "photo": null,
      "groups": [
        "waterloo",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-ayush-kapur",
      "side": null,
      "parents": []
    },
    {
      "id": "jason-lee",
      "name": "Jason Lee",
      "photo": null,
      "groups": [
        "meta-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "danielle-lavigne",
      "name": "Danielle Lavigne",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-brandon-lavigne",
      "side": null,
      "parents": []
    },
    {
      "id": "julia-lavigne",
      "name": "Julia Lavigne",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-brandon-lavigne",
      "side": null,
      "parents": []
    },
    {
      "id": "angela-gu",
      "name": "Angela Gu",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-angela-gu",
      "side": null,
      "parents": []
    },
    {
      "id": "rae-bennett",
      "name": "Rae Bennett",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "jasper-chapman-black",
      "name": "Jasper Chapman-Black",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-jasper-chapman-black",
      "side": null,
      "parents": []
    },
    {
      "id": "stacey-chapman-black",
      "name": "Stacey Chapman-Black",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-jasper-chapman-black",
      "side": null,
      "parents": []
    },
    {
      "id": "brandon-lavigne",
      "name": "Brandon Lavigne",
      "photo": null,
      "groups": [
        "meta-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-brandon-lavigne",
      "side": null,
      "parents": []
    },
    {
      "id": "chelsi-manhas",
      "name": "Chelsi Manhas",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-chelsi-manhas",
      "side": null,
      "parents": []
    },
    {
      "id": "svetomir-milanovic",
      "name": "Svetomir Milanovic",
      "photo": "/narsh2026/images/people/svetomir.jpeg",
      "groups": [
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-nicole-fleury",
      "side": null,
      "parents": []
    },
    {
      "id": "william-fleury",
      "name": "William Fleury",
      "photo": "/narsh2026/images/people/william.jpg",
      "groups": [
        "natalies-family",
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "mary-fleury"
      ]
    },
    {
      "id": "nicole-fleury",
      "name": "Nicole Fleury",
      "photo": "/narsh2026/images/people/nicole.jpg",
      "groups": [
        "natalies-family",
        "cayman-crew"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-nicole-fleury",
      "side": "natalie",
      "parents": []
    },
    {
      "id": "kyle-katchaluba",
      "name": "Kyle Katchaluba",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-chelsi-manhas",
      "side": null,
      "parents": []
    },
    {
      "id": "bradley-ramunas",
      "name": "Bradley Ramunas",
      "photo": null,
      "groups": [
        "stripe-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "natalie-tchokreff",
      "name": "Natalie Tchokreff",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-george-utsin",
      "side": null,
      "parents": []
    },
    {
      "id": "george-utsin",
      "name": "George Utsin",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-george-utsin",
      "side": null,
      "parents": []
    },
    {
      "id": "kyle-francis",
      "name": "Kyle Francis",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-kendra-kusick",
      "side": "natalie",
      "parents": []
    },
    {
      "id": "jonah-dlin",
      "name": "Jonah Dlin",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-dina-dlin",
      "side": null,
      "parents": []
    },
    {
      "id": "hannah-dobrik",
      "name": "Hannah Dobrik",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-hannah-dobrik",
      "side": null,
      "parents": []
    },
    {
      "id": "nariyan-krsnadas",
      "name": "Nariyan Krsnadas",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-gaea-turman",
      "side": null,
      "parents": []
    },
    {
      "id": "ryan-drapeau",
      "name": "Ryan Drapeau",
      "photo": null,
      "groups": [
        "stripe-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "manjot-nagra",
      "name": "Manjot Nagra",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "spencer-dobrik",
      "name": "Spencer Dobrik",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-hannah-dobrik",
      "side": null,
      "parents": []
    },
    {
      "id": "sabrina-wasserman",
      "name": "Sabrina Wasserman",
      "photo": null,
      "groups": [
        "meta-coworkers",
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "dina-dlin",
      "name": "Dina Dlin",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-dina-dlin",
      "side": null,
      "parents": []
    },
    {
      "id": "stephen-melinyshyn",
      "name": "Stephen Melinyshyn",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-ashley-darton",
      "side": null,
      "parents": []
    },
    {
      "id": "ashley-darton",
      "name": "Ashley Darton",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-ashley-darton",
      "side": null,
      "parents": []
    },
    {
      "id": "claire-hsu",
      "name": "Claire Hsu",
      "photo": null,
      "groups": [
        "stripe-coworkers"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "shawna-huang",
      "name": "Shawna Huang",
      "photo": null,
      "groups": [
        "stripe-coworkers"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "isaac-madwed",
      "name": "Isaac Madwed",
      "photo": null,
      "groups": [
        "stripe-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-celine-rosak",
      "side": null,
      "parents": []
    },
    {
      "id": "brenda-morehouse",
      "name": "Brenda Morehouse",
      "photo": "/narsh2026/images/people/brenda.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "sidney-morehouse"
      ]
    },
    {
      "id": "alexandre-bondoux",
      "name": "Alexandre Bondoux",
      "photo": null,
      "groups": [
        "stripe-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "evan-morehouse",
      "name": "Evan Morehouse",
      "photo": "/narsh2026/images/people/evan.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": [
        "brenda-morehouse"
      ]
    },
    {
      "id": "celine-rosak",
      "name": "Celine Rosak",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-celine-rosak",
      "side": null,
      "parents": []
    },
    {
      "id": "sam-showalter",
      "name": "Sam Showalter",
      "photo": null,
      "groups": [
        "stripe-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-sam-showalter",
      "side": null,
      "parents": []
    },
    {
      "id": "david-mediati",
      "name": "David Mediati",
      "photo": null,
      "groups": [
        "waterloo"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-christina-antinora",
      "side": null,
      "parents": []
    },
    {
      "id": "christina-antinora",
      "name": "Christina Antinora",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-christina-antinora",
      "side": null,
      "parents": []
    },
    {
      "id": "sarah-zhou",
      "name": "Sarah Zhou",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-sam-showalter",
      "side": null,
      "parents": []
    },
    {
      "id": "amy-hung",
      "name": "Amy Hung",
      "photo": null,
      "groups": [
        "stripe-coworkers",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "maddie-hayman",
      "name": "Maddie Hayman",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "giao-nguyen",
      "name": "Giao Nguyen",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-giao-nguyen",
      "side": null,
      "parents": []
    },
    {
      "id": "tom-yang",
      "name": "Tom Yang",
      "photo": null,
      "groups": [
        "waterloo",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-giao-nguyen",
      "side": null,
      "parents": []
    },
    {
      "id": "alex-hayman",
      "name": "Alex Hayman",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "shannan-young",
      "name": "Shannan Young",
      "photo": null,
      "groups": [
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "chantal-cossette",
      "name": "Chantal Cossette",
      "photo": null,
      "groups": [],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "david-lu",
      "name": "David Lu",
      "photo": null,
      "groups": [
        "meta-coworkers",
        "waterloo",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "anmol-mago",
      "name": "Anmol Mago",
      "photo": null,
      "groups": [
        "meta-coworkers",
        "waterloo",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "tiffany-yeung",
      "name": "Tiffany Yeung",
      "photo": null,
      "groups": [
        "waterloo",
        "seattleite"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "seth-hendrickson",
      "name": "Seth Hendrickson",
      "photo": null,
      "groups": [
        "stripe-coworkers"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "josh-jhinger",
      "name": "Josh Jhinger",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "nimret-malhi",
      "name": "Nimret Malhi",
      "photo": null,
      "groups": [
        "abby-friends"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": null,
      "parents": []
    },
    {
      "id": "mary-fleury",
      "name": "Mary Fleury",
      "photo": "/narsh2026/images/people/mary.jpg",
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "natalie",
      "parents": []
    },
    {
      "id": "jatinder-kaur",
      "name": "Jatinder Kaur",
      "photo": "/narsh2026/images/people/jatinder.jpg",
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": []
    },
    {
      "id": "amritpal-rai",
      "name": "Amritpal Rai",
      "photo": "/narsh2026/images/people/amritpal.jpg",
      "groups": [
        "arashs-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": null,
      "side": "arash",
      "parents": []
    },
    {
      "id": "janessa-reimer",
      "name": "Janessa Reimer",
      "photo": null,
      "groups": [
        "natalies-family"
      ],
      "cities": [],
      "isCouple": false,
      "funFact": null,
      "connectionToCouple": null,
      "householdId": "household-glen-antle",
      "side": "natalie",
      "parents": [
        "glen-antle",
        "jennifer-reimer"
      ]
    }
  ];

  const EDGES = [
    {
      "source": "natalie",
      "target": "arash",
      "type": "couple"
    },
    {
      "source": "natalie",
      "target": "shawna-morehouse",
      "type": "parent"
    },
    {
      "source": "natalie",
      "target": "william-fleury",
      "type": "parent"
    },
    {
      "source": "arash",
      "target": "jatinder-kaur",
      "type": "parent"
    },
    {
      "source": "arash",
      "target": "amritpal-rai",
      "type": "parent"
    },
    {
      "source": "rene-fleury",
      "target": "mary-fleury",
      "type": "parent"
    },
    {
      "source": "katelyn-henry",
      "target": "rene-fleury",
      "type": "parent"
    },
    {
      "source": "natreisha-henry",
      "target": "rene-fleury",
      "type": "parent"
    },
    {
      "source": "ben-blumer",
      "target": "steve-blumer",
      "type": "parent"
    },
    {
      "source": "jennifer-reimer",
      "target": "rene-fleury",
      "type": "parent"
    },
    {
      "source": "jillian-reimer",
      "target": "glen-antle",
      "type": "parent"
    },
    {
      "source": "jillian-reimer",
      "target": "jennifer-reimer",
      "type": "parent"
    },
    {
      "source": "shiloh-riddell",
      "target": "serenity-blumer",
      "type": "parent"
    },
    {
      "source": "taliah-riddell",
      "target": "serenity-blumer",
      "type": "parent"
    },
    {
      "source": "serenity-blumer",
      "target": "steve-blumer",
      "type": "parent"
    },
    {
      "source": "isaiah-riddell",
      "target": "serenity-blumer",
      "type": "parent"
    },
    {
      "source": "shawna-morehouse",
      "target": "sidney-morehouse",
      "type": "parent"
    },
    {
      "source": "shannon-noble",
      "target": "heather-morehouse",
      "type": "parent"
    },
    {
      "source": "heather-morehouse",
      "target": "sidney-morehouse",
      "type": "parent"
    },
    {
      "source": "james-noble",
      "target": "heather-morehouse",
      "type": "parent"
    },
    {
      "source": "karen-morehouse",
      "target": "sidney-morehouse",
      "type": "parent"
    },
    {
      "source": "rosanne-fleury",
      "target": "mary-fleury",
      "type": "parent"
    },
    {
      "source": "gabrielle-blumer",
      "target": "steve-blumer",
      "type": "parent"
    },
    {
      "source": "gabrielle-blumer",
      "target": "rosanne-fleury",
      "type": "parent"
    },
    {
      "source": "william-fleury",
      "target": "mary-fleury",
      "type": "parent"
    },
    {
      "source": "brenda-morehouse",
      "target": "sidney-morehouse",
      "type": "parent"
    },
    {
      "source": "evan-morehouse",
      "target": "brenda-morehouse",
      "type": "parent"
    },
    {
      "source": "janessa-reimer",
      "target": "glen-antle",
      "type": "parent"
    },
    {
      "source": "janessa-reimer",
      "target": "jennifer-reimer",
      "type": "parent"
    },
    {
      "source": "rene-fleury",
      "target": "rosanne-fleury",
      "type": "sibling"
    },
    {
      "source": "rene-fleury",
      "target": "william-fleury",
      "type": "sibling"
    },
    {
      "source": "rosanne-fleury",
      "target": "william-fleury",
      "type": "sibling"
    },
    {
      "source": "katelyn-henry",
      "target": "natreisha-henry",
      "type": "sibling"
    },
    {
      "source": "katelyn-henry",
      "target": "jennifer-reimer",
      "type": "sibling"
    },
    {
      "source": "natreisha-henry",
      "target": "jennifer-reimer",
      "type": "sibling"
    },
    {
      "source": "ben-blumer",
      "target": "serenity-blumer",
      "type": "sibling"
    },
    {
      "source": "ben-blumer",
      "target": "gabrielle-blumer",
      "type": "sibling"
    },
    {
      "source": "serenity-blumer",
      "target": "gabrielle-blumer",
      "type": "sibling"
    },
    {
      "source": "jillian-reimer",
      "target": "janessa-reimer",
      "type": "sibling"
    },
    {
      "source": "shiloh-riddell",
      "target": "taliah-riddell",
      "type": "sibling"
    },
    {
      "source": "shiloh-riddell",
      "target": "isaiah-riddell",
      "type": "sibling"
    },
    {
      "source": "taliah-riddell",
      "target": "isaiah-riddell",
      "type": "sibling"
    },
    {
      "source": "shawna-morehouse",
      "target": "heather-morehouse",
      "type": "sibling"
    },
    {
      "source": "shawna-morehouse",
      "target": "karen-morehouse",
      "type": "sibling"
    },
    {
      "source": "shawna-morehouse",
      "target": "brenda-morehouse",
      "type": "sibling"
    },
    {
      "source": "heather-morehouse",
      "target": "karen-morehouse",
      "type": "sibling"
    },
    {
      "source": "heather-morehouse",
      "target": "brenda-morehouse",
      "type": "sibling"
    },
    {
      "source": "karen-morehouse",
      "target": "brenda-morehouse",
      "type": "sibling"
    },
    {
      "source": "shannon-noble",
      "target": "james-noble",
      "type": "sibling"
    }
  ];

  const HOUSEHOLDS = [
    {
      "id": "household-cindy-fleury",
      "members": [
        "cindy-fleury",
        "rene-fleury"
      ],
      "displayName": "Cindy & Rene"
    },
    {
      "id": "household-katelyn-henry",
      "members": [
        "katelyn-henry",
        "natreisha-henry"
      ],
      "displayName": "Katelyn & Natreisha"
    },
    {
      "id": "household-glen-antle",
      "members": [
        "jennifer-reimer",
        "glen-antle",
        "jillian-reimer",
        "janessa-reimer"
      ],
      "displayName": "Jennifer, Glen, Jillian & Janessa"
    },
    {
      "id": "household-isaiah-riddell",
      "members": [
        "shiloh-riddell",
        "taliah-riddell",
        "serenity-blumer",
        "isaiah-riddell"
      ],
      "displayName": "Shiloh, Taliah, Serenity & Isaiah"
    },
    {
      "id": "household-farzad-sangi",
      "members": [
        "sumita-barahmand",
        "farzad-sangi"
      ],
      "displayName": "Sumita & Farzad"
    },
    {
      "id": "household-georgia-hong",
      "members": [
        "jerry-liu",
        "georgia-hong"
      ],
      "displayName": "Jerry & Georgia"
    },
    {
      "id": "household-kendra-kusick",
      "members": [
        "kendra-kusick",
        "kyle-francis"
      ],
      "displayName": "Kendra & Kyle"
    },
    {
      "id": "household-amy-qiu",
      "members": [
        "amy-qiu",
        "phillip-vo"
      ],
      "displayName": "Amy & Phillip"
    },
    {
      "id": "household-greg-bennett",
      "members": [
        "greg-bennett",
        "leighanne-bennett"
      ],
      "displayName": "Greg & Leighanne"
    },
    {
      "id": "household-angela-gu",
      "members": [
        "bill-chen",
        "angela-gu"
      ],
      "displayName": "Bill & Angela"
    },
    {
      "id": "household-james-hageman",
      "members": [
        "james-hageman",
        "sarah-baird"
      ],
      "displayName": "James & Sarah"
    },
    {
      "id": "household-heather-morehouse",
      "members": [
        "shannon-noble",
        "heather-morehouse",
        "james-noble"
      ],
      "displayName": "Shannon, Heather & James"
    },
    {
      "id": "household-gabrielle-blumer",
      "members": [
        "rosanne-fleury",
        "steve-blumer",
        "gabrielle-blumer"
      ],
      "displayName": "Rosanne, Steve & Gabrielle"
    },
    {
      "id": "household-grace-jean",
      "members": [
        "matt-dsouza",
        "grace-jean"
      ],
      "displayName": "Matt & Grace"
    },
    {
      "id": "household-gaea-turman",
      "members": [
        "gaea-turman",
        "nariyan-krsnadas"
      ],
      "displayName": "Gaea & Nariyan"
    },
    {
      "id": "household-annie-huang",
      "members": [
        "logan-howard",
        "annie-huang"
      ],
      "displayName": "Logan & Annie"
    },
    {
      "id": "household-geoffrey-solomon",
      "members": [
        "teresa-solomon",
        "geoffrey-solomon"
      ],
      "displayName": "Teresa & Geoffrey"
    },
    {
      "id": "household-ayush-kapur",
      "members": [
        "emma-park",
        "ayush-kapur"
      ],
      "displayName": "Emma & Ayush"
    },
    {
      "id": "household-brandon-lavigne",
      "members": [
        "danielle-lavigne",
        "julia-lavigne",
        "brandon-lavigne"
      ],
      "displayName": "Danielle, Julia & Brandon"
    },
    {
      "id": "household-jasper-chapman-black",
      "members": [
        "jasper-chapman-black",
        "stacey-chapman-black"
      ],
      "displayName": "Jasper & Stacey"
    },
    {
      "id": "household-chelsi-manhas",
      "members": [
        "chelsi-manhas",
        "kyle-katchaluba"
      ],
      "displayName": "Chelsi & Kyle"
    },
    {
      "id": "household-nicole-fleury",
      "members": [
        "svetomir-milanovic",
        "nicole-fleury"
      ],
      "displayName": "Svetomir & Nicole"
    },
    {
      "id": "household-george-utsin",
      "members": [
        "natalie-tchokreff",
        "george-utsin"
      ],
      "displayName": "Natalie & George"
    },
    {
      "id": "household-dina-dlin",
      "members": [
        "jonah-dlin",
        "dina-dlin"
      ],
      "displayName": "Jonah & Dina"
    },
    {
      "id": "household-hannah-dobrik",
      "members": [
        "hannah-dobrik",
        "spencer-dobrik"
      ],
      "displayName": "Hannah & Spencer"
    },
    {
      "id": "household-ashley-darton",
      "members": [
        "stephen-melinyshyn",
        "ashley-darton"
      ],
      "displayName": "Stephen & Ashley"
    },
    {
      "id": "household-celine-rosak",
      "members": [
        "isaac-madwed",
        "celine-rosak"
      ],
      "displayName": "Isaac & Celine"
    },
    {
      "id": "household-sam-showalter",
      "members": [
        "sam-showalter",
        "sarah-zhou"
      ],
      "displayName": "Sam & Sarah"
    },
    {
      "id": "household-christina-antinora",
      "members": [
        "david-mediati",
        "christina-antinora"
      ],
      "displayName": "David & Christina"
    },
    {
      "id": "household-giao-nguyen",
      "members": [
        "giao-nguyen",
        "tom-yang"
      ],
      "displayName": "Giao & Tom"
    }
  ];

  const MARRIAGES = [
    {
      "a": "shawna-morehouse",
      "b": "william-fleury",
      "side": "natalie"
    },
    {
      "a": "amritpal-rai",
      "b": "jatinder-kaur",
      "side": "arash"
    },
    {
      "a": "glen-antle",
      "b": "jennifer-reimer",
      "side": "natalie"
    },
    {
      "a": "rosanne-fleury",
      "b": "steve-blumer",
      "side": "natalie"
    }
  ];

  const getGuestById = (id) => GUESTS.find(g => g.id === id) || null;
  const getGuestsByGroup = (groupId) => GUESTS.filter(g => g.groups.includes(groupId));
  const getGuestsByCity = (cityId) => GUESTS.filter(g => g.cities.includes(cityId));
  const searchGuests = (query) => {
    const q = query.trim().toLowerCase();
    if (!q) return [];
    return GUESTS.filter(g => g.name.toLowerCase().includes(q));
  };

  const getSocialNodes = () => {
    const householdMap = new Map();
    HOUSEHOLDS.forEach(h => { h.members.forEach(m => householdMap.set(m, h)); });
    const processed = new Set();
    const socialNodes = [];
    GUESTS.forEach(guest => {
      if (processed.has(guest.id)) return;
      const household = householdMap.get(guest.id);
      if (household) {
        household.members.forEach(m => processed.add(m));
        const members = household.members.map(m => getGuestById(m)).filter(Boolean);
        const allGroups = [...new Set(members.flatMap(m => m.groups))];
        const allCities = [...new Set(members.flatMap(m => m.cities))];
        const photo = members.find(m => m.photo)?.photo || null;
        const isCouple = members.some(m => m.isCouple);
        socialNodes.push({
          id: household.id, name: household.displayName, photo,
          groups: allGroups, cities: allCities, isCouple,
          memberIds: household.members, isHousehold: true
        });
      } else {
        processed.add(guest.id);
        socialNodes.push({
          id: guest.id, name: guest.name, photo: guest.photo,
          groups: guest.groups, cities: guest.cities, isCouple: guest.isCouple,
          memberIds: [guest.id], isHousehold: false
        });
      }
    });
    return socialNodes;
  };

  const getSocialEdges = (socialNodes) => {
    const nodeIdSet = new Set(socialNodes.map(n => n.id));
    const memberToNodeId = new Map();
    socialNodes.forEach(n => { n.memberIds.forEach(m => memberToNodeId.set(m, n.id)); });
    const edgeSet = new Set();
    const remapped = [];
    EDGES.forEach(edge => {
      const sourceId = memberToNodeId.get(edge.source) || edge.source;
      const targetId = memberToNodeId.get(edge.target) || edge.target;
      if (sourceId === targetId) return;
      if (!nodeIdSet.has(sourceId) || !nodeIdSet.has(targetId)) return;
      const key = [sourceId, targetId].sort().join("--");
      if (edgeSet.has(key)) return;
      edgeSet.add(key);
      remapped.push({ source: sourceId, target: targetId, type: edge.type });
    });
    return remapped;
  };

  return {
    GROUPS, CITIES, GUESTS, EDGES, HOUSEHOLDS, MARRIAGES,
    getGuestById, getGuestsByGroup, getGuestsByCity, searchGuests,
    getSocialNodes, getSocialEdges
  };
})();
